#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# n8n-copilot-free  —  One-shot setup script
# Deploys n8n + GitHub Copilot as a free local LLM backend via Docker Compose.
#
# Requirements: Docker + Docker Compose v2, bash, curl, openssl
# Usage:        bash setup.sh
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.env"
ENV_FILE="${SCRIPT_DIR}/.env"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"

# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[info]${RESET}  $*"; }
ok()      { echo -e "${GREEN}[ok]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET}  $*"; }
error()   { echo -e "${RED}[error]${RESET} $*" >&2; }
header()  { echo -e "\n${BOLD}${CYAN}══ $* ══${RESET}"; }

# ── pre-flight ────────────────────────────────────────────────────────────────
header "Pre-flight checks"

if ! command -v docker &>/dev/null; then
  error "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
  exit 1
fi
ok "Docker found: $(docker --version)"

# Accept both 'docker compose' (v2 plugin) and 'docker-compose' (v1 standalone)
if docker compose version &>/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE="docker-compose"
else
  error "Docker Compose not found. Install it: https://docs.docker.com/compose/install/"
  exit 1
fi
ok "Compose found: $($COMPOSE version)"

if [[ ! -f "$CONFIG_FILE" ]]; then
  error "config.env not found at ${CONFIG_FILE}"
  exit 1
fi

# ── load config ───────────────────────────────────────────────────────────────
header "Loading configuration"

# Source safely — only grab known variables
# shellcheck source=config.env
source <(grep -E '^[A-Z_]+=.*' "$CONFIG_FILE" | grep -v '^#')

N8N_PORT="${N8N_PORT:-5678}"
COPILOT_API_PORT="${COPILOT_API_PORT:-4141}"
COPILOT_SHIM_PORT="${COPILOT_SHIM_PORT:-4142}"
COPILOT_API_VERSION="${COPILOT_API_VERSION:-0.7.0}"
DB_USER="${DB_USER:-n8n}"
DB_PASSWORD="${DB_PASSWORD:-changeme123}"
DB_NAME="${DB_NAME:-n8n}"
N8N_HOST="${N8N_HOST:-localhost}"
N8N_PROTOCOL="${N8N_PROTOCOL:-http}"
N8N_EDITOR_BASE_URL="${N8N_EDITOR_BASE_URL:-http://localhost:${N8N_PORT}}"
WEBHOOK_URL="${WEBHOOK_URL:-http://localhost:${N8N_PORT}/webhook}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-Change@Me123}"

info "Desired ports → n8n:${N8N_PORT}  copilot-api:${COPILOT_API_PORT}  shim:${COPILOT_SHIM_PORT}"

# ── port checker ──────────────────────────────────────────────────────────────
header "Port availability check"

# Returns 0 if port is free, 1 if in use
port_in_use() {
  local port="$1"
  # Try ss first (Linux), fall back to netstat, fall back to /dev/tcp
  if command -v ss &>/dev/null; then
    ss -tlnp 2>/dev/null | grep -q ":${port} " && return 0 || return 1
  elif command -v netstat &>/dev/null; then
    netstat -tlnp 2>/dev/null | grep -q ":${port} " && return 0 || return 1
  else
    # Bash /dev/tcp fallback (no external tool needed)
    (echo >/dev/tcp/127.0.0.1/"$port") 2>/dev/null && return 0 || return 1
  fi
}

# Find next available port starting from $1
next_free_port() {
  local port="$1"
  while port_in_use "$port"; do
    warn "Port ${port} is already in use — trying $((port+1))"
    port=$((port + 1))
  done
  echo "$port"
}

N8N_PORT=$(next_free_port "$N8N_PORT")
COPILOT_API_PORT=$(next_free_port "$COPILOT_API_PORT")
COPILOT_SHIM_PORT=$(next_free_port "$COPILOT_SHIM_PORT")

ok "Resolved ports → n8n:${N8N_PORT}  copilot-api:${COPILOT_API_PORT}  shim:${COPILOT_SHIM_PORT}"

# ── generate secrets if not set ───────────────────────────────────────────────
header "Secrets"

# Read from config.env values
CFG_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY:-}"
CFG_JWT_SECRET="${JWT_SECRET:-}"

if [[ -z "$CFG_ENCRYPTION_KEY" ]]; then
  CFG_ENCRYPTION_KEY="$(openssl rand -hex 24)"
  info "Generated N8N_ENCRYPTION_KEY (saved to .env)"
else
  info "Using N8N_ENCRYPTION_KEY from config.env"
fi

if [[ -z "$CFG_JWT_SECRET" ]]; then
  CFG_JWT_SECRET="$(openssl rand -hex 24)"
  info "Generated JWT_SECRET (saved to .env)"
else
  info "Using JWT_SECRET from config.env"
fi

# ── write .env ─────────────────────────────────────────────────────────────────
header "Writing .env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# Do not edit by hand — re-run setup.sh to regenerate.

# Ports (auto-resolved)
N8N_PORT=${N8N_PORT}
COPILOT_API_PORT=${COPILOT_API_PORT}
COPILOT_SHIM_PORT=${COPILOT_SHIM_PORT}

# copilot-api
COPILOT_API_VERSION=${COPILOT_API_VERSION}

# Database
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}

# n8n
N8N_HOST=${N8N_HOST}
N8N_PROTOCOL=${N8N_PROTOCOL}
N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
WEBHOOK_URL=${WEBHOOK_URL}
N8N_ENCRYPTION_KEY=${CFG_ENCRYPTION_KEY}
JWT_SECRET=${CFG_JWT_SECRET}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

ok ".env written to ${ENV_FILE}"

# ── pull images ───────────────────────────────────────────────────────────────
header "Pulling Docker images"
$COMPOSE --env-file "$ENV_FILE" -f "$COMPOSE_FILE" pull --quiet
ok "Images pulled"

# ── start stack ───────────────────────────────────────────────────────────────
header "Starting services"
$COMPOSE --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d
ok "All containers started"

# ── wait for copilot-api ──────────────────────────────────────────────────────
header "Waiting for copilot-api to be ready"

echo -n "  Waiting"
MAX_WAIT=120
ELAPSED=0
until curl -sf "http://localhost:${COPILOT_API_PORT}/v1/models" &>/dev/null; do
  if [[ $ELAPSED -ge $MAX_WAIT ]]; then
    echo ""
    # copilot-api may need auth before /models works — check if it's at least listening
    if curl -sf --max-time 2 "http://localhost:${COPILOT_API_PORT}/" &>/dev/null || \
       curl -s --max-time 2 "http://localhost:${COPILOT_API_PORT}/v1/models" | grep -q "code\|error\|auth\|login" 2>/dev/null; then
      ok "copilot-api is listening (needs GitHub auth — see below)"
      break
    fi
    warn "copilot-api did not become ready within ${MAX_WAIT}s. Checking logs..."
    docker logs copilot-api --tail 20 2>&1 | sed 's/^/  /'
    break
  fi
  echo -n "."
  sleep 3
  ELAPSED=$((ELAPSED + 3))
done
echo ""

# ── GitHub device auth ────────────────────────────────────────────────────────
header "GitHub Copilot Authentication"

echo ""
echo -e "  ${BOLD}You need to authenticate once with your GitHub account.${RESET}"
echo ""
echo "  1. Run this command to get your one-time auth code:"
echo ""
echo -e "     ${YELLOW}docker exec -it copilot-api copilot-api auth${RESET}"
echo ""
echo "  2. It will print a code like:  ${BOLD}XXXX-XXXX${RESET}"
echo "     Open this URL in your browser and enter the code:"
echo -e "     ${CYAN}https://github.com/login/device${RESET}"
echo ""
echo "  3. Approve access with your GitHub account (Copilot must be active)."
echo ""
echo "  The auth token is stored in a Docker volume and persists across restarts."
echo ""
read -rp "  Press Enter once you have completed GitHub auth to continue..."

# ── verify shim ───────────────────────────────────────────────────────────────
header "Verifying shim"

if curl -sf "http://localhost:${COPILOT_SHIM_PORT}/v1/models" &>/dev/null; then
  ok "Shim is reachable at http://localhost:${COPILOT_SHIM_PORT}/v1"
else
  warn "Could not reach shim on port ${COPILOT_SHIM_PORT}. Check: docker logs copilot-shim"
fi

# ── wait for n8n ──────────────────────────────────────────────────────────────
header "Waiting for n8n"

echo -n "  Waiting"
ELAPSED=0
until curl -sf "http://localhost:${N8N_PORT}/healthz" &>/dev/null; do
  if [[ $ELAPSED -ge 90 ]]; then
    echo ""
    warn "n8n did not respond within 90s. Check: docker logs n8n-app"
    break
  fi
  echo -n "."
  sleep 3
  ELAPSED=$((ELAPSED + 3))
done
echo ""
ok "n8n is up"

# ── final instructions ────────────────────────────────────────────────────────
header "Setup complete"

echo ""
echo -e "  ${GREEN}${BOLD}Everything is running!${RESET}"
echo ""
echo -e "  ${BOLD}n8n URL:${RESET}           http://localhost:${N8N_PORT}"
echo -e "  ${BOLD}Admin password:${RESET}    ${ADMIN_PASSWORD}"
echo ""
echo -e "  ${BOLD}${CYAN}Configure n8n to use GitHub Copilot as AI:${RESET}"
echo "  ─────────────────────────────────────────"
echo "  1. Open n8n → Settings → Credentials → New"
echo "  2. Search for: OpenAI"
echo "  3. Set:"
echo -e "       Base URL:  ${YELLOW}http://copilot-shim:${COPILOT_SHIM_PORT}/v1${RESET}"
echo -e "       API Key:   ${YELLOW}dummy${RESET}"
echo "  4. Save and use this credential in any AI Agent node or Personal Agents chat."
echo ""
echo -e "  ${BOLD}Useful commands:${RESET}"
echo "  docker logs -f copilot-shim       # watch AI request translation"
echo "  docker logs -f copilot-api        # watch upstream Copilot calls"
echo "  $COMPOSE --env-file .env -f docker-compose.yml down   # stop all"
echo "  $COMPOSE --env-file .env -f docker-compose.yml up -d  # start all"
echo ""
echo -e "  ${BOLD}To re-run setup (e.g. after editing config.env):${RESET}"
echo "  bash setup.sh"
echo ""
